### ISSUE TITLE
keras_contrib.callbacks.DeadReluDetector: IndexError: list index out of range

### ISSUE THREAD

**Issue by rola93** [keras-team/keras-contrib#261]
It seems that layers without weights raise this error, for example whit batchNormalization. I'm not sure if this migth happen with another layer.

I'm following [this tutorial](https://blog.keras.io/building-autoencoders-in-keras.html) and modified it a little to add a batch normalization layer. Here goes the code:

```
from keras.layers import Input, Dense, Conv2D, MaxPooling2D, UpSampling2D, Activation, BatchNormalization
from keras.models import Model
from keras import backend as K

input_img = Input(shape=(28, 28, 1))  # adapt this if using `channels_first` image data format

x = Conv2D(16, (3, 3), padding='same')(input_img)
x = BatchNormalization()(x)
x = Activation('relu')(x)
x = MaxPooling2D((2, 2), padding='same')(x)
x = Conv2D(8, (3, 3), activation='relu', padding='same')(x)
x = MaxPooling2D((2, 2), padding='same')(x)
x = Conv2D(8, (3, 3), activation='relu', padding='same')(x)
encoded = MaxPooling2D((2, 2), padding='same')(x)

# at this point the representation is (4, 4, 8) i.e. 128-dimensional

x = Conv2D(8, (3, 3), activation='relu', padding='same')(encoded)
x = UpSampling2D((2, 2))(x)
x = Conv2D(8, (3, 3), activation='relu', padding='same')(x)
x = UpSampling2D((2, 2))(x)
x = Conv2D(16, (3, 3), activation='relu')(x)
x = UpSampling2D((2, 2))(x)
decoded = Conv2D(1, (3, 3), activation='sigmoid', padding='same')(x)

autoencoder = Model(input_img, decoded)
autoencoder.compile(optimizer='adadelta', loss='binary_crossentropy')

from keras.datasets import mnist
import numpy as np

(x_train, _), (x_test, _) = mnist.load_data()

x_train = x_train.astype('float32') / 255.
x_test = x_test.astype('float32') / 255.
x_train = np.reshape(x_train, (len(x_train), 28, 28, 1))  # adapt this if using `channels_first` image data format
x_test = np.reshape(x_test, (len(x_test), 28, 28, 1))  # adapt this if using `channels_first` image data format

from keras.callbacks import TensorBoard
from keras_contrib.callbacks.dead_relu_detector import DeadReluDetector

autoencoder.fit(x_train[:20], x_train[:20],
                epochs=2,
                batch_size=10,
                shuffle=True,
                validation_data=(x_test[:10], x_test[:10]),
                callbacks=[DeadReluDetector(x_train[:10]), TensorBoard(log_dir='/tmp/autoencoder/mnist')])

```
I have it in bug.py and when I run it, throws:

```
$ python bug.py 
/home/rola93/.pyenv/versions/env/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Train on 20 samples, validate on 10 samples
Epoch 1/2
20/20 [==============================] - 1s 27ms/step - loss: 0.6968 - val_loss: 0.5968
Traceback (most recent call last):
  File "bug.py", line 47, in <module>
    callbacks=[DeadReluDetector(x_train[:10]), TensorBoard(log_dir='/tmp/autoencoder/mnist')])
  File "/home/rola93/.pyenv/versions/env/lib/python3.6/site-packages/keras/engine/training.py", line 1705, in fit
    validation_steps=validation_steps)
  File "/home/rola93/.pyenv/versions/env/lib/python3.6/site-packages/keras/engine/training.py", line 1256, in _fit_loop
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/rola93/.pyenv/versions/env/lib/python3.6/site-packages/keras/callbacks.py", line 77, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/home/rola93/.pyenv/versions/env/lib/python3.6/site-packages/keras_contrib/callbacks/dead_relu_detector.py", line 58, in on_epoch_end
    for relu_activation in self.get_relu_activations():
  File "/home/rola93/.pyenv/versions/env/lib/python3.6/site-packages/keras_contrib/callbacks/dead_relu_detector.py", line 54, in get_relu_activations
    layer_weight_shape = np.shape(layer_weight[0])
IndexError: list index out of range

```

*proposed solution*
I wonder if asking for empty list is enougth for this, something like that:

```
# [line 45]
for layer_index, layer_activations in enumerate(layer_outputs):
            if self.is_relu_layer(self.model.layers[layer_index]):
                layer_name = self.model.layers[layer_index].name
                # layer_weight is a list [W] (+ [b])
                layer_weight = self.model.layers[layer_index].get_weights()
                # with kernel and bias, the weights are saved as a list [W, b]. If only weights, it is [W]
                if type(layer_weight) is not list:
                    raise ValueError("'Layer_weight' should be a list, but was {}".format(type(layer_weight)))

                # solution begin
                if len(layer_weight) == 0:
                    # there are no weigths for current layer, skip it
                    continue
                # solution end

                layer_weight_shape = np.shape(layer_weight[0])
                yield [layer_index, layer_activations, layer_name, layer_weight_shape]
```

however, since I'm newby with Keras I don't see what else should change and the effects on this being changed (perhaps some consistency check later need to be changed too or something like that)

I'm running it in Ubuntu 16.04, from a pyenv virtualenv on python 3.6.4, with Keras==2.1.6, Keras==2.1.6, tensorboard==1.8.0, tensorflow==1.8.0, numpy==1.14.3

**Comment by rola93** [comment]
Thanks for your suggestion but I'm also using batch normalization, so I need to use it as a layer, don't I?

I used my proposed solution locally and it seems to work, please let me know when this fix is available :smile:

**Comment by arodiss** [comment]
Yes, if you want to put BN inbetween convolution and activation you need separate layer
You can subscribe to mentioned PR and gt notification when it's merged. Don't expect it to be very soon though
