### ISSUE TITLE
CRF with semantic segmentation network. Shapes are not compatible error.

### ISSUE THREAD

**Issue by ajaskier** [keras-team/keras-contrib#288]
I have troubles with integration of semantic segmentation network and CRF layer.

This is the chunk of code where I'm trying to build a network:

```python
input_shape=(512, 512, 3)
n_class=1
inputs = keras.Input(input_shape, dtype='float32')
enc, skip = self.encoder(inputs)
bottom = self.bottom(enc)
dec = self.decoder(bottom, skip)
classify = layers.Conv2D(n_class, (1, 1), activation='sigmoid')(dec)

crf = CRF(n_class, learn_mode='marginal')(classify)
model = models.Model(inputs=inputs, outputs=crf)
```

The first 7 lines are responsible for building Unet-like architecture. Then I would like to add CRF on top of that. When I run this code this is the output that I get:

<details>
<summary>Output</summary>

```
/usr/local/lib/python3.6/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/tensor_shape.py", line 670, in merge_with
    new_dims.append(dim.merge_with(other[i]))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/tensor_shape.py", line 143, in merge_with
    self.assert_is_compatible_with(other)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/tensor_shape.py", line 116, in assert_is_compatible_with
    other))
ValueError: Dimensions 1 and 512 are not compatible

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 112, in <module>
    fire.Fire(train)
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 366, in _Fire
    component, remaining_args)
  File "/usr/local/lib/python3.6/dist-packages/fire/core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "train.py", line 46, in train
    crf=config.crf)
  File "/home/user/workspace/project/network/models/management.py", line 48, in __init__
    self.model = self.build_model(model_builder_kwargs)
  File "/home/user/workspace/project/network/models/management.py", line 110, in build_model
    model = builder(self.target_size)
  File "/home/user/workspace/project/network/models/unet.py", line 262, in __call__
    crf = CRF(n_class, learn_mode='marginal')(classify)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/topology.py", line 619, in __call__
    output = self.call(inputs, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/keras_contrib/layers/crf.py", line 236, in call
    test_output = self.get_marginal_prob(X, mask)
  File "/usr/local/lib/python3.6/dist-packages/keras_contrib/layers/crf.py", line 495, in get_marginal_prob
    alpha = self.forward_recursion(input_energy, mask=mask, input_length=input_length)
  File "/usr/local/lib/python3.6/dist-packages/keras_contrib/layers/crf.py", line 485, in forward_recursion
    return self.recursion(input_energy, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/keras_contrib/layers/crf.py", line 475, in recursion
    input_length=input_length, unroll=self.unroll)
  File "/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py", line 2767, in rnn
    swap_memory=True)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 3224, in while_loop
    result = loop_context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2956, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2893, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py", line 2758, in _step
    new_state.set_shape(state.get_shape())
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 512, in set_shape
    self._shape_val = self.shape.merge_with(shape)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/tensor_shape.py", line 673, in merge_with
    raise ValueError("Shapes %s and %s are not compatible" % (self, other))
ValueError: Shapes (?, 1, 1) and (?, 512, 1) are not compatible
m
```

</details>

I don't really know what is the root cause of this error so any help is appreciated.

**Comment by brownpanther** [comment]
hi alexsander, did you figure this out?

**Comment by brownpanther** [comment]
I read another GitHub issue that said this is because the crf layer in keras right now is for sequential data and not spatial image data. That's probably the reason.
