### ISSUE TITLE
Can't import keras-contrib with keras2.2.1+

### ISSUE THREAD

**Issue by keisen** [keras-team/keras-contrib#291]
```
$ python
Python 3.5.5 (default, Jul 11 2018, 05:47:58) 
[GCC 7.2.1 20170915 (Red Hat 7.2.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import keras_contrib
/home/ec2-user/.pyenv/versions/3.5.5/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Using TensorFlow backend.
/home/ec2-user/.pyenv/versions/3.5.5/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/ec2-user/.pyenv/versions/3.5.5/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/ec2-user/.pyenv/versions/3.5.5_test/lib/python3.5/site-packages/matplotlib/__init__.py:1067: UserWarning: Duplicate key in file "/home/ec2-user/.config/matplotlib/matplotlibrc", line #2
  (fname, cnt))
/home/ec2-user/.pyenv/versions/3.5.5_test/lib/python3.5/site-packages/matplotlib/__init__.py:1067: UserWarning: Duplicate key in file "/home/ec2-user/.config/matplotlib/matplotlibrc", line #3
  (fname, cnt))
/home/ec2-user/.pyenv/versions/3.5.5/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ec2-user/.pyenv/versions/3.5.5_test/lib/python3.5/site-packages/keras_contrib/__init__.py", line 4, in <module>
    from . import layers
  File "/home/ec2-user/.pyenv/versions/3.5.5_test/lib/python3.5/site-packages/keras_contrib/layers/__init__.py", line 3, in <module>
    from .convolutional import *
  File "/home/ec2-user/.pyenv/versions/3.5.5_test/lib/python3.5/site-packages/keras_contrib/layers/convolutional.py", line 15, in <module>
    from keras.utils.conv_utils import normalize_data_format
ImportError: cannot import name 'normalize_data_format'
>>>
``` 

`keras.utils.conv_utils#normalize_data_format()` already moved into `keras.backend.common` .
For details, please see below.

https://github.com/keras-team/keras/pull/10690

**Comment by wilderrodrigues** [comment]
I'm looking into it.

**Comment by yuyijie1995** [comment]
Have you solve this problem?

**Comment by keisen** [comment]
@yuyijie1995 , I created a PR #292 . Please refer to it.

**Comment by romanovzky** [comment]
Looking forward to the PR merge!

**Comment by keisen** [comment]
Hi, @haramoz .
Currently, keras-contrib has compatibility with keras2.2.1+.
So you need to update keras to 2.2.1+ or to downgrade keras-contrib to several previous revisions.

**Comment by haramoz** [comment]
ok thank you for your comment. to clarify further, I have keras 2.2.2 and tensorflow 1.10. Is trying to use keras_contrib Densenet.py with my own data. However it gives me std::bad_alloc error. Do you think this is a separate issue or somehow related to the correct versions of the keras/tf/keras_contrib ? THa

**Comment by keisen** [comment]
I'm not sure. At least, I have not faced the error.
