### ISSUE TITLE
LearningRateMultiplier with ModelCheckpoint raise TypeError

### ISSUE THREAD

**Issue by InsightDev** [keras-team/keras-contrib#399]
I use LearningRateMultiplier, when I add ModelCheckpoint to keras fit's callbacks, it raise TypeError.

steps_per_epoch=5, epochs=500, callbacks=mCallbacks);
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/training.py", line 2177, in fit_generator
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/training_generator.py", line 216, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/callbacks.py", line 214, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/callbacks.py", line 601, in on_epoch_end
    self.model.save(filepath, overwrite=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/network.py", line 1363, in save
    save_model(self, filepath, overwrite, include_optimizer)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/keras/engine/saving.py", line 134, in save_model
    default=serialization.get_json_type).encode('utf8')
  File "/usr/lib/python2.7/json/__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/serialization.py", line 41, in get_json_type
    return {'class_name': obj.__class__.__name__, 'config': obj.get_config()}
TypeError: unbound method get_config() must be called with Adam instance as first argument (got nothing instead)

It seems the get_config() should be called with instance(self._optimizer), but not called with classs(self._class)

        config = {'optimizer': **self._class**,
                  'lr_multipliers': self._lr_multipliers}
        base_config = self._optimizer.get_config()
        return dict(list(base_config.items()) + list(config.items()))

**Comment by InsightDev** [comment]
EXAMPLE:

optimizer = Adam()
print optimizer.__class__.__name__;
config = optimizer.get_config();

optimizer = Adam;
print optimizer.__class__.__name__;
config = optimizer.get_config();

OUTPUT:
Adam
type
Traceback (most recent call last):
  File "......./type_error.py", line 12, in <module>
    config = optimizer.get_config();
TypeError: unbound method get_config() must be called with Adam instance as first argument (got nothing instead)

**Comment by gabrieldemarmiesse** [comment]
lr_multiplier is not merged into master yet. Once it's merged into master, it will be properly tested and only then you should expect it to work.
