### ISSUE TITLE
tf2.0 error

### ISSUE THREAD

**Issue by SilverLiningSL** [keras-team/keras-contrib#527]
I'm trying to use keras_contrib with tf2.0. Sure I followed the instruction 'Install keras_contrib for tensorflow.keras'.
But when I tried to import with
```python
from keras_contrib.layers.crf import CRF
```
I got the error below:
```python
Traceback (most recent call last):
  File "/Users/silverlining/学习项目/Multi-task-lmm/Multi_task.py", line 23, in <module>
    from keras_contrib.layers.crf import CRF
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/Users/silverlining/anaconda3/envs/tf2/lib/python3.7/site-packages/tf_keras_contrib-2.0.8-py3.7.egg/keras_contrib/__init__.py", line 4, in <module>
    # Licensed under the Apache License, Version 2.0 (the "License");
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/Users/silverlining/anaconda3/envs/tf2/lib/python3.7/site-packages/tf_keras_contrib-2.0.8-py3.7.egg/keras_contrib/layers/__init__.py", line 3, in <module>
    #
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/Users/silverlining/anaconda3/envs/tf2/lib/python3.7/site-packages/tf_keras_contrib-2.0.8-py3.7.egg/keras_contrib/layers/advanced_activations/pelu.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/Users/silverlining/anaconda3/envs/tf2/lib/python3.7/site-packages/tf_keras_contrib-2.0.8-py3.7.egg/keras_contrib/utils/test_utils.py", line 188, in <module>
KeyError: 'Cannot detect if using keras or tf.keras.'

Process finished with exit code 1
```
Anyone have idea for this?

**Comment by bthorsted** [comment]
I have the same issue. The problem is that `keras-contrib` checks for the keras distribution by calling `keras.__name__` and compares it as shown here:

```python
if keras.__name__ == 'keras':
    is_tf_keras = False
elif keras.__name__ == 'tensorflow.keras':
    is_tf_keras = True
else:
    raise KeyError('Cannot detect if using keras or tf.keras.')
```
however, for `tensorflow(-gpu) 2.*` this attribute is actually `tensorflow_core.python.keras.api._v2.keras` and therefore it will forever fail unless the check is changed to something more sensible. I would suggest simply editing line 188 from `elif keras.__name__ == 'tensorflow.keras':` to `elif 'tensorflow' in keras.__name__:` as that will solve the issue.

**Comment by sara-02** [comment]
@bjtho08 Can you please help with which file needs editing, I installed contribs for tf using these steps https://github.com/keras-team/keras-contrib#install-keras_contrib-for-tensorflowkeras and currently on tf 2.2

**Comment by bthorsted** [comment]
> @bjtho08 Can you please help with which file needs editing, I installed contribs for tf using these steps https://github.com/keras-team/keras-contrib#install-keras_contrib-for-tensorflowkeras and currently on tf 2.2
> 

It's been a while since I looked at this, but as far as I can tell, you need to locate the file https://github.com/keras-team/keras-contrib/blob/master/keras_contrib/utils/test_utils.py which has the following lines:
 

```
elif​ ​keras​.​__name__​ ​==​ ​'tensorflow.keras'​: 
 ​    ​is_tf_keras​ ​=​ ​True
```

And then change it like I suggested. But maybe it would be easier, and better, if you migrate to the Tensorflow.addons library instead of the deprecated keras-contrib library. The latest version also has the CRF layer. https://github.com/tensorflow/addons
